/*
 * This file is generated by jOOQ.
*/
package com.hellokoding.jooq.model;


import com.hellokoding.jooq.model.tables.Browserverification;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.browserVerification</code>.
     */
    public static final Browserverification BROWSERVERIFICATION = com.hellokoding.jooq.model.tables.Browserverification.BROWSERVERIFICATION;
}
