/*
 * This file is generated by jOOQ.
*/
package com.hellokoding.jooq.model.tables.records;


import com.hellokoding.jooq.model.tables.Browserverification;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BrowserverificationRecord extends TableRecordImpl<BrowserverificationRecord> implements Record3<String, String, Timestamp> {

    private static final long serialVersionUID = -936546990;

    /**
     * Setter for <code>test.browserVerification.email</code>.
     */
    public void setEmail(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.browserVerification.email</code>.
     */
    public String getEmail() {
        return (String) get(0);
    }

    /**
     * Setter for <code>test.browserVerification.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.browserVerification.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.browserVerification.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.browserVerification.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Browserverification.BROWSERVERIFICATION.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Browserverification.BROWSERVERIFICATION.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Browserverification.BROWSERVERIFICATION.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrowserverificationRecord value1(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrowserverificationRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrowserverificationRecord value3(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrowserverificationRecord values(String value1, String value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BrowserverificationRecord
     */
    public BrowserverificationRecord() {
        super(Browserverification.BROWSERVERIFICATION);
    }

    /**
     * Create a detached, initialised BrowserverificationRecord
     */
    public BrowserverificationRecord(String email, String code, Timestamp createdat) {
        super(Browserverification.BROWSERVERIFICATION);

        set(0, email);
        set(1, code);
        set(2, createdat);
    }
}
